# -*- coding: utf-8 -*-
"""Maria_Kausar_rdd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OhpmSDNhAgVFL0IluvL7fy88VvSixBPO

# Load Clinicialtrial Dataset
"""

# Make variable and load dataset file
fileroot = "clinicaltrial_2023"
pharma = "pharma"

import os

# Set the environment variable 'fileroot' to the value of the variable 'fileroot'
os.environ['fileroot'] = fileroot

# Set the environment variable 'pharma' to the value of the variable 'pharma'
os.environ['pharma'] = pharma

dbutils.fs.ls("FileStore/tables")

# Commented out IPython magic to ensure Python compatibility.
# %sh
# Use UNIX Command to Verify that All the files are Safely Copid to tmp Directiory
ls /tmp/

"""# Unzip by Variable, Preprocessing"""

# Commented out IPython magic to ensure Python compatibility.
# %sh

# Use UNIX Commands to UNZIP files

rm -r /tmp/$fileroot
rm /tmp/$fileroot.zip

rm -r /tmp/$pharma
rm /tmp/$pharma.zip

## Clean the local file system from the contents that the notebook needs to create again

## Clean the DBFS from the contents that the notebook needs to create again
dbutils.fs.rm("/FileStore/tables/" + fileroot , True)
dbutils.fs.rm("/FileStore/tables/" + pharma , True)

# Copy the file with the name 'fileroot.zip' from the directory
dbutils.fs.cp("/FileStore/tables/" + fileroot + ".zip", "file:/tmp/")

# Same above copy the file with the name 'pharma.zip'
dbutils.fs.cp("/FileStore/tables/" + pharma + ".zip", "file:/tmp/")

# Commented out IPython magic to ensure Python compatibility.
# %sh
# Use the %sh magic command to run shell commands within the notebook cell

# Unzip the file 'fileroot.zip' located in the '/tmp' directory and extract its contents to the '/tmp' directory
unzip -d /tmp /tmp/$fileroot.zip

# Unzip the file 'pharma.zip'
unzip -d /tmp /tmp/$pharma.zip

# Move the CSV file from the '/tmp' directory to the '/FileStore/tables/' directory
dbutils.fs.mv("file:/tmp/"+fileroot+".csv", "/FileStore/tables/", True)

# Move the CSV file from the '/tmp' to the '/FileStore/tables/' directory
dbutils.fs.mv("file:/tmp/"+pharma+".csv", "/FileStore/tables/", True)

# List the files and directories
dbutils.fs.ls("/FileStore/tables/")

# Display the first few lines
dbutils.fs.head("/FileStore/tables/"+fileroot+".csv")

"""# Cleaning and Preprocessing using RDD

"""

# Create RDD and display 2 records
RDD_pharma = sc.textFile("/FileStore/tables/"+pharma+".csv")
RDD_pharma.take(2)

# Create myRDD on 2023 dataset,than, split each line by newline character "\n".
myRDD = sc.textFile("/FileStore/tables/"+fileroot+".csv"). \
    map(lambda line: line.split("\n"))

# Display the first 3 records of the RDD
myRDD.take(2)

# Replace double quotes with an empty string
myRDD2 = myRDD.map(lambda x: x[0].replace('"',''))

# Display the first 10 records of the new RDD 'myRDD2'
myRDD2.take(10)

## Replace commas with an empty string in each element of 'myRDD2' and take 5 records
myRDD3 = myRDD2.map(lambda x: x.replace(",",""))

#Ensure each field has 14 elements
myRDD3.map(lambda field: field + [None]*(14-len(field)))

# Show the first few elements
myRDD3.take(3)

# Skip the first row of records
skippedRDD = myRDD3.zipWithIndex().filter(lambda x: x[1] > 0).map(lambda x: x[0])

# Remove null rows
filteredRDD = skippedRDD.filter(lambda row: all(element is not None for element in row))

# Take 10 records after removing null rows
filteredRecords = filteredRDD.take(10)

# Print the result
for record in filteredRecords:
    print(record)

# Split each element of 'myRDD3' by the tab character "\t"
myRDD4 = myRDD3.map(lambda x: x.split("\t"))

# Display the first 10 records
myRDD4.take(5)

# Skip the first row of records
cleaned_RDD = myRDD4.zipWithIndex().filter(lambda x: x[1] > 0).map(lambda x: x[0])
cleaned_RDD.take(3)

"""# Problem statements by using RDD"""

# Problem statement 1
num_of_rows = cleaned_RDD.count()
print("Number of studies in the dataset are:", num_of_rows)

import matplotlib.pyplot as plt

# Assuming 'cleaned_RDD' is your RDD containing the data
num_of_rows = cleaned_RDD.count()

# Create a bar plot
plt.bar(["Number of Studies"], [num_of_rows], color='skyblue')

# Add title and labels
plt.title("Number of Studies in the Dataset")
plt.ylabel("Number of Studies")

# Show plot
plt.show()

"""Problem 2


"""

import matplotlib.pyplot as plt

def create_column_rdd(myRDD4, column_name):
    # Find the index of the column by searching through the first row of the RDD
    header_row = myRDD4.first()
    column_index = None
    for i, col in enumerate(header_row):
        if col == column_name:
            column_index = i
            break

    if column_index is not None:
        # Use the column index to extract the column value
        myRDD = myRDD4.map(lambda x: (x[column_index] if len(x) > column_index else '', 1))
        return myRDD
    else:
        print(f"Column '{column_name}' not found in the RDD.")
        return None

# Example usage:
column_name = 'Type'
myRDD = create_column_rdd(myRDD4, column_name)

# Continue with the rest of your code
if myRDD:
    frequency_myRDD = myRDD.reduceByKey(lambda a, b: a + b)
    sorted_myRDD = frequency_myRDD.sortByKey()  # Sort in ascending order
    output = sorted_myRDD.takeOrdered(10, key=lambda x: -x[1])  # Take top 10, sorted by frequency
    # print(output)

    output_filtered = [(column, count) for column, count in output if column != column_name]
    print(output_filtered)

    # Extract data for visualization
    values = [x[0] for x in output_filtered]
    counts = [x[1] for x in output_filtered]

    # Plotting
    plt.figure(figsize=(10, 6))
    plt.bar(values, counts, color='skyblue')
    plt.xlabel(column_name)
    plt.ylabel('Frequency')
    plt.title(f'Top 10 Frequencies of {column_name}')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

"""Problem 3:
 Top five conditions ( from conditions ) with their frequencies
"""

import matplotlib.pyplot as plt

# Assign key value to all conditions
column_index = 4
conditions_myRDD = cleaned_RDD.map(lambda x: (x[column_index] if len(x) > column_index else '', 1))

# Sum individually key values
sum_conditions_myRDD = conditions_myRDD.reduceByKey(lambda a,b: a+b)

# Find the top 5 key-value pairs with the highest values
top_5_conditions = sum_conditions_myRDD.takeOrdered(5, key=lambda x: -x[1])

# Print the top 5 key-value pairs
for pair in top_5_conditions:
    print(pair)

# Extract data for visualization
values = [x[0] for x in top_5_conditions]
counts = [x[1] for x in top_5_conditions]

# Plotting
plt.figure(figsize=(10, 6))
plt.bar(values, counts, color='skyblue')
plt.xlabel("Condition")
plt.ylabel('Frequency')
plt.title('Top 5 Conditions by Frequency')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Problem 4"""

# Assuming myRDD4 contains clinical trial data and RDD_pharma contains pharmaceutical companies

# Extract sponsors from myRDD4
myRDD4_sponsors = myRDD4.map(lambda x: (x[6], 1))

# Extract pharmaceutical companies from RDD_pharma
pharma_companies = RDD_pharma.map(lambda x: (x.split(',')[1], None))

# Left outer join to find sponsors in myRDD4 that are not in RDD_pharma
non_pharma_sponsors = myRDD4_sponsors.leftOuterJoin(pharma_companies).filter(lambda x: x[1][1] is None)

# Count the number of clinical trials sponsored by each sponsor
sponsors_with_counts = non_pharma_sponsors.map(lambda x: (x[0], x[1][0])).reduceByKey(lambda a, b: a + b)

# Find the 10 most common sponsors
top_10_sponsors = sponsors_with_counts.takeOrdered(10, key=lambda x: -x[1])

# Print the result
for sponsor, count in top_10_sponsors:
    print(f"{sponsor}: {count}")

import matplotlib.pyplot as plt

# Extract data for visualization
sponsors = [x[0] for x in top_10_sponsors]
counts = [x[1] for x in top_10_sponsors]

# Plotting
plt.figure(figsize=(10, 6))
plt.barh(sponsors, counts, color='skyblue')
plt.xlabel('Number of Clinical Trials')
plt.ylabel('Sponsor')
plt.title('Top 10 Sponsors of Clinical Trials (Non-Pharmaceutical Companies)')
plt.gca().invert_yaxis()  # Invert y-axis to have the highest count at the top
plt.tight_layout()
plt.show()

"""# Problem 5"""

import matplotlib.pyplot as plt
# Filter the RDD to include only the rows where the year is '2023' and the status is 'COMPLETED'
completed_trials_rdd = myRDD4_.filter(lambda x: x[13][:4] == '2023' and x[3] == 'COMPLETED')

# Map the RDD to extract the "Status" and the first 7 characters of the "Completion" column
status_completion_rdd = completed_trials_rdd.map(lambda x: (x[3], x[13][:7]))

# Filter the RDD to include only the rows where the year is '2023' and the status is 'COMPLETED'
completed_trials_rdd = myRDD4_.filter(lambda x: x[13][:4] == '2023' and x[3] == 'COMPLETED')

# Map the RDD to extract the status and the first 7 characters of the completion date
status_completion_rdd = completed_trials_rdd.map(lambda x: (x[3], x[13][:7]))

# Map the RDD to extract the status and the month
month_rdd = status_completion_rdd.map(lambda x: (x[0], int(x[1][5:7])))

# Filter out months that are between 1 and 12
valid_month_rdd = month_rdd.filter(lambda x: 1 <= x[1] <= 12)

# Map the RDD to extract the months
month_rdd = status_completion_rdd.map(lambda x: int(x[1][5:7]))

# Filter out months that are between 1 and 12
valid_month_rdd = month_rdd.filter(lambda x: 1 <= x <= 12)

# Define a dictionary for month names
month_names = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 5: "May", 6: "Jun",
    7: "Jul", 8: "Aug", 9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}

# Map the RDD to convert month numbers to month names
month_names_rdd = month_rdd.map(lambda x: month_names.get(x))

# Filter out any None values from month_names_rdd
filtered_month_names_rdd = month_names_rdd.filter(lambda x: x is not None)

# Map each month name to a tuple (month_name, 1) for counting
month_counts_rdd = filtered_month_names_rdd.map(lambda x: (x, 1)).reduceByKey(lambda x, y: x + y)

# # Collect the first 12 elements (assuming there are 12 unique months)
# monthly_counts = month_counts_rdd.take(12)

# # Extract month names and their frequencies
# months = [month[0] for month in monthly_counts]
# frequencies = [month[1] for month in monthly_counts]

# # Plotting the graph
# plt.figure(figsize=(10, 6))
# plt.bar(months, frequencies, color='skyblue')
# plt.xlabel('Month')
# plt.ylabel('Frequency')
# plt.title('Monthly Completion Frequency in 2023')
# plt.xticks(rotation=45)  # Rotate x-axis labels for better visibility
# plt.grid(axis='y', linestyle='--', alpha=0.7)
# plt.tight_layout()
# plt.show()

